swagger: '2.0'
info:
  title: for-api-gateway
  description: API on API Gateway with a Cloud Run backend
  version: 2.0.0
schemes:
- https
produces:
- application/json
securityDefinitions:
  api_key:
    type: apiKey
    name: X-API-Key
    in: header
security:
  - api_key: []
paths:
  /:
    get:
      x-google-backend:
        address: Cloud RunのURL
        path_translation: APPEND_PATH_TO_ADDRESS
      summary: for api gateway
      operationId: getApiGateway
      responses:
        '200':
          description: A successful response
          schema:
            type: string
        '401':
          description: Unauthorized - Invalid or missing API key
          schema:
            $ref: '#/definitions/Error'
